apiVersion: v1
kind: Namespace
metadata:
  name: istio-intranet
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-intranet
  namespace: istio-intranet
spec:
  gatewayClassName: istio-gatewayclass-intranet
  infrastructure:
    labels:
      app: istio-gateway
    parametersRef:
      group: ""
      kind: ConfigMap
      name: gateway-intranet-config  
  # Only Routes from the same namespace are allowed.
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All  #or All or Selector
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-intranet-config
  namespace: istio-intranet
data:
  deployment: |
    metadata:
      annotations:
        gateway-default-setting: test
    spec:
      replicas: 3
  service: |
    spec:
      type: NodePort
      ports:
        - name: http
          port: 80
          targetPort: 80
          nodePort: 31000